### ISSUE TITLE
import code action not working in scala 3.0.0.RC1 project

### ISSUE THREAD

**Issue by caenrique** [scalameta/nvim-metals#104]
**Describe the bug**

Creating a project using the scala3 template in metals and trying to use something that needs to be imported doesn't trigger a code action for importing it. If triggered manually, it says: `No code action available`

**To Reproduce** Steps to reproduce the behavior:

1. Create new project with `metals.new-scala-project` using `scala/scala3.g8` template
2. Write a line in `Main.scala` using something that needs to be imported like `Try`, `Future`, `UUID`, etc

**Expected behavior**

A dialog should pop up prompting me to import the corresponding thing on enter

**Installation:**

- Operating system: macOS
- Nvim version: NVIM v0.4.4
- Commit of nvim-metals: af357ef
- Metals version: v0.10.0

**Comment by ckipp01** [comment]
Thanks for the report @caenrique! This is due to auto imports not yet being implemented for Scala 3 in Metals. You can find the feature request for this here https://github.com/scalameta/metals-feature-requests/issues/113.

As a total aside, is your NVIM version correct? nvim-metals requires nvim 0.5.x so I'm surprised to see v.0.4.4?

**Comment by caenrique** [comment]
Thanks for the response @ckipp01 ! 
Oh I just realized that this repo is for the native lsp client in nvim 🤦🏽‍♂️ amd I'm using coc-metals. Sorry 😅

**Comment by ckipp01** [comment]
Ahh ok, all good then!

**Comment by landerlo** [comment]
And metals Tungsten 0.10.0 is here! scala 3.0.0-RC1 working fine
