### ISSUE TITLE
Support even more multi-module project hierarchies

### ISSUE THREAD

**Issue by tymcauley** [scalameta/nvim-metals#257]
**Describe the feature**

In #6 (and then subsequently in #37), the [`find_root_dir`](https://github.com/scalameta/nvim-metals/blob/0d5ff68afcd2db4bb35acd516229dec80092f176/lua/metals/util.lua#L23) function was added to support nested project roots. The [`validate_config` function](https://github.com/scalameta/nvim-metals/blob/0d5ff68afcd2db4bb35acd516229dec80092f176/lua/metals/config.lua#L131) uses that function to set the `root_dir` LSP config string. I would love to override that setting to support some stranger multi-module project hierarchies (see "Additional context").

**Potential ways to implement?**

I don't know exactly how we want to make that happen, but I currently have two ideas:

1. Change that line of `validate_config` to allow users to set their own root dir, like this:
```lua
config.root_dir = config.root_dir or util.find_root_dir...
```
2. Add more complicated logic to the `find_root_dir` function to support weirder nestings of project hierarchies.

I would imagine that most users are happy with the existing setup, and going with option 2 might lead to inadvertent problems for those users. Going with option 1 would be pretty simple, and allow users to customize this however they want. If this strange project hierarchy (see "Additional context") ends up being a common use-case (I'd be surprised if that happened, but who knows...), then we could revisit option 2 in the future.

**Additional context**

I regularly work on a project that has a directory structure that looks like this:

```
./
├── build.sbt
├── dir1/
│  └── dir2/
│     ├── build.sbt
│     └── src/
│        └── main/
│           └── scala/
└── src/
   └── main/
      └── scala/
```

Right now, if I ever open a `.scala` file underneath the `dir2` hirerarchy, the root-level `build.sbt` file won't be found. This is due to how the [`find_root_dir`](https://github.com/scalameta/nvim-metals/blob/0d5ff68afcd2db4bb35acd516229dec80092f176/lua/metals/util.lua#L23) function is implemented, which looks for root files either in the current directory or the direct parent. This organization would require looking yet another level above.

**Search terms**

config, root_dir

**Comment by ckipp01** [comment]
Hey @tymcauley! Thanks for opening this. I'll be honest, I've never actually seen a structure like this where there's two levels between build files, so I totally haven't thought about it. In theory we could check for this, but again, not sure how common this. I'm not opposed to doing this, but would want to ensure I have better tests doing this before adding that in... and I'm also planning on removing a bunch of that code to utilize logic from https://github.com/nvim-lua/plenary.nvim#plenarypath.

With that being said, one quick thing we could do maybe is introduce a `config.find_root_dir` that allows the user to pass in a function that can be used instead of my own `util.find_root_dir`. Then you could include your own logic to check multiple layers down or that function can just return the exact path you want. Do you think this would work for you?

Thanks for the detailed issue and explanation.

**Comment by ckipp01** [comment]
> I'd be happy to submit a PR getting started with that.

That would be great. This is pretty much exactly what I would do.
