### ISSUE TITLE
javaHome setting is not respected

### ISSUE THREAD

**Issue by jpalus** [scalameta/nvim-metals#380]
### Describe the bug

It seems that `javaHome` setting is ignored by metals, can't really tell if that's `nvim-metals` issue or `metals` itself.

`JAVA_HOME` env var is respected when it comes to `bloop` server but note that there is another `java` process that ignores both `javaHome` setting and `JAVA_HOME` env var that I suppose is used to start `metals` itself (`java  -Xss4m -Xms100m -jar $XDG_CACHE_HOME/nvim/nvim-metals/metals`)

### Expected behavior

If configured `javaHome` setting should be used by all java processes.

### Operating system

Linux

### Version of Metals

v0.11.5

### Commit of nvim-metals

1d49ab74afb9f4934db9d856c5e93e591addcf14

**Comment by ckipp01** [comment]
So this is a bit tricky due to the way that `nvim-metals` bootstraps Metals. When you do a `:MetalsInstall` or `:MetalsUpdate` it will use `cs bootstrap` which will create a `metals` executable. That executable if you look at it is actually just a shell script that calls `java`, so there isn't a good way for that setting to impact what version of Java Metals gets started with. So it's preferable just to use `JAVA_HOME` instead with the version of Java you'll want. I'll think about this a bit more.

**Comment by ckipp01** [comment]
Hey @jpalus I'm revisiting this today as I still don't see a good way around this unless we put together the full classpath and java path and pass that to Neovim to start Metals with. However, I also noticed you said

> JAVA_HOME env var is respected when it comes to bloop server but note that there is another java process that ignores both javaHome setting and JAVA_HOME env var that I suppose is used to start metals itself (java -Xss4m -Xms100m -jar $XDG_CACHE_HOME/nvim/nvim-metals/metals)

Testing this I do get that the metals process does respect `JAVA_HOME`. Just to verify, you're saying that in your scenario this isn't respecting what you have set as `JAVA_HOME`?

**Comment by jpalus** [comment]
@ckipp01 After starting `nvim` with `metals` project I have two new processes:
1. One with `-jar $XDG_CACHE_HOME/nvim/nvim-metals/metals` -- does not respect `JAVA_HOME`
2. `bloop` server -- respects JAVA_HOME

Neither of them respects `javaHome` setting, only `JAVA_HOME` env var.

My ad-hoc workaround was to modify `$XDG_CACHE_HOME/nvim/nvim-metals/metals` combined script/JAR to use `JAVA_HOME` if present so instead of:
```
exec java '-Xss4m' '-Xms100m' $JAVA_OPTS "$@"
```
used:
```
exec "${JAVA_HOME:+$JAVA_HOME/bin/}java" '-Xss4m' '-Xms100m' $JAVA_OPTS "$@"
```

**Comment by ckipp01** [comment]
Gotcha, thanks @jpalus. I'll have to think still more on this. The solution to fix this would be to do what we do in VS Code for example and grab the java home java with some logic, get the entire classpath for metals, and then instead of creating a metals executable, we literally pass in `java <full metals classpath>`. We then have control over everything. That's quite a bit of more work to set up, so I'm hoping to maybe find a good way to get the coursier script to respect `JAVA_HOME`.

**Comment by ckipp01** [comment]
Alright, so the change to coursier is merged in, so now `JAVA_HOME` will be respected when Metals is started. The new version of coursier was also released so if you update, and then re-install metals you can see inside of the `metals` executable:

```
[ -x "$JAVA_HOME/bin/java" ] && JAVA_CMD="$JAVA_HOME/bin/java" || JAVA_CMD=java
exec $JAVA_CMD '-Xss4m' '-Xms100m' $JAVA_OPTS "$@"
```
I've also made a note about this in the docs to make it clear that the `javaHome` setting won't actually be used to _start_ metals. I think for now, this is as close as we're going to get with full control unless we change the way we bootstrap metals in `nvim-metals` and I don't think it's worth it at the moment to make that change unless a lot of people want it. So for now I'll close this. Thanks for bringing up the topic @jpalus, and comment back if you have any other thoughts.
