### ISSUE TITLE
Support the Decoration Protocol

### ISSUE THREAD

**Issue by ckipp01** [scalameta/nvim-metals#4]
**Describe the feature**

Metals can publish worksheet evaluation using the [Decoration Protocol](https://scalameta.org/metals/docs/editors/decoration-protocol.html). Nvim has support for this using virtual text, and this is implemented in [coc-metals](https://github.com/scalameta/coc-metals/blob/master/src/decoration.ts) and it wasn't a ton of work.

**Search terms**

decoration protocol, worksheets

**Comment by landerlo** [comment]
Have you started working on this?

**Comment by ckipp01** [comment]
Hey @landerlo! Not yet, so if you want to give it a go, have at it.

**Comment by ckipp01** [comment]
Btw, one thing to also note with this is that you'll want to also implement [`metals/didFocusTextDocument`](https://scalameta.org/metals/docs/editors/new-editor.html#metalsdidfocustextdocument) with this. There has been issues in a couple clients with the worksheets not being updated after the initial time, and it was due to this.

**Comment by ckipp01** [comment]
Hey @landerlo, were you still planning on tackling this? If not, I have some free time and was thinking about giving it a go.

**Comment by landerlo** [comment]
Hi, yes, I have something almost ready, I think I'll have some time to polish the PR tomorrow evening. I was testing it last night but I was having some issues with didFocus, metals doesn't seem to like it, and triggers some stack overflows. So I'll split that functionality to another PR, I don't think it's relevant to us, because what's needed for worksheets is to send didSave, nvim-metals only sends didChange at the moment, which works for normal scala files, but for worksheets, that's not triggering the decoration publication. DidSave notification is required in order to the worksheet to update. Maybe a bug in metals but we can workaround that by configuring the options to save.

**Comment by landerlo** [comment]
PR here https://github.com/scalameta/nvim-metals/pull/22, 
It had a few headscratchers about some metals behaviour. First, it doesn't seem to send decorations on change, it only updates them on didFocus or didSave. Now only didSave is supported, which is fine by me, I want the reevaluation to happen on save anyway.
Another odd thing is that the httpEnabled option needs to be set, otherwise decorations don't work. I'd have thought that it had a false default. I'll send didFocus on additional PR but metals seems to have internal stack overflows when it receives the notification.

**Comment by ckipp01** [comment]
Awesome, I'll start taking a look at it. Couple first thoughts:

> It had a few headscratchers about some metals behaviour. First, it doesn't seem to send decorations on change, it only updates them on didFocus or didSave.

If I understand you correctly, this is expected. You wouldn't want to send new decorations as the user is typing, and that's be impossible with how Metals works, so it requires the save event or the focus even to both evaluate and send. Am I understanding what you mean correctly?

> Now only didSave is supported, which is fine by me, I want the reevaluation to happen on save anyway.

I don't believe this is actually the case from the Metals side of things. I just checked and verified with coc-metals and the latest version of Metals that the `metals/publishDecorations` does happen when a `metals/didFocusTextDocument` is sent to the server. I'll try to see if I can see what's going on when I review the code.

> Another odd thing is that the httpEnabled option needs to be set, otherwise decorations don't work. I'd have thought that it had a false default. I'll send didFocus on additional PR but metals seems to have internal stack overflows when it receives the notification.

This is odd behavior indeed. I'm not sure why that would be the case. We'll have to figure out what's going on because we need `httpEnabled` in order for Doctor to work. Regarding the stack overflow, that also shouldn't be happening 🤔

**Comment by landerlo** [comment]
> Awesome, I'll start taking a look at it. Couple first thoughts:
> 
> > It had a few headscratchers about some metals behaviour. First, it doesn't seem to send decorations on change, it only updates them on didFocus or didSave.
> 
> If I understand you correctly, this is expected. You wouldn't want to send new decorations as the user is typing, and that's be impossible with how Metals works, so it requires the save event or the focus even to both evaluate and send. Am I understanding what you mean correctly?

Yes, and on second thought, it makes sense to be the actual behaviour.

> > Now only didSave is supported, which is fine by me, I want the reevaluation to happen on save anyway.
> 
> I don't believe this is actually the case from the Metals side of things. I just checked and verified with coc-metals and the latest version of Metals that the `metals/publishDecorations` does happen when a `metals/didFocusTextDocument` is sent to the server. I'll try to see if I can see what's going on when I review the code.

I meant with this PR decoration is only refreshed on saves, as didFocus is taken to another PR  because it was throwing some exceptions in metals, it's on another PR I've sent after this. If we merge the didFocus PR then yes, the decorations are refreshed on refocus, even the unsaved changes, but I'm not bothered about this, in fact I might even prefer the consistency that it's always refreshed on save. Not with the leaving vim and returning to vim event, thought this could be changed if we add more autocommands that sent the didFocus, like one that reopens the buffer. Feel free to extend the didFocus PR.

> > Another odd thing is that the httpEnabled option needs to be set, otherwise decorations don't work. I'd have thought that it had a false default. I'll send didFocus on additional PR but metals seems to have internal stack overflows when it receives the notification.
> 
> This is odd behavior indeed. I'm not sure why that would be the case. We'll have to figure out what's going on because we need `httpEnabled` in order for Doctor to work. Regarding the stack overflow, that also shouldn't be happening thinking

**Comment by ckipp01** [comment]
> Yes, and on second thought it makes sense to be the expected behaviour. The other confusing bit is that I thought didSave was already being sent, but it isn't, so I had to enable it with the on_init which is a bit hacky, but I couldn't see any way to enable it unless metals sends a full TextDocumentSyncOptions json object instead of just a number.

Yea, agreed, it's not ideal. I actually posted a question in the nvim gitter channel about this because I noticed some odd behavior with the defaults, and I'm unsure why this works in all other clients up to this point, but not here.

> We could ask nvim-lsp to change this to enable didSave when the number is received, IMO it makes more sense, but it might be rejected because of backward compatibility.

Yea, the odd thing is that I'm not 100% sure that's actually according to spec. When looking at it I see:

> If present will save notifications are sent to the server. If omitted the notification should not be sent.

So I guess if you send a number, it's not present right?

> Not with the leaving vim and returning to vim event, thought this could be changed if we add more autocommands that sent the didFocus, like one that moves to the buffer from another buffer in vim. Feel free to extend the didFocus PR.

Regarding this stuff, I put a note in the pr, but I _believe_ there is a bug if we don't do this where if you leave the buffer and go to another file, and then come back to the worksheet buffer a didSave won't even re-trigger it.

**Comment by ckipp01** [comment]
@landerlo I actually opened https://github.com/scalameta/metals/pull/1837 which  when testing locally with a snapshot will allow us to just remove the `on_init`. I think this is actually more accurate that Metals explicitly states that it wants the `save` events.

**Comment by landerlo** [comment]
Thank you, that will allow for the flexibility we need and we can remove the on_init hack

**Comment by ckipp01** [comment]
> Thank you, that will allow for the flexibility we need and we can remove the on_init hack

So I removed this, and I changed the request to a notify fixing the pr that you had. I'm going to leave this open until we figure out the hover to show the extra information, but I have an idea for that.
