### ISSUE TITLE
Quick Worksheet if file already exists

### ISSUE THREAD

**Issue by susliko** [scalameta/nvim-metals#504]
### Describe the feature

Now invoking the "Quick Worksheet" command twice in a row results in an error from Metals. The error reports about file duplicate:
```
java.nio.file.FileAlreadyExistsException: The file /.../X.worksheet.sc already exists.
```

Probably, a more robust behavior here would be to open the existing file instead of showing the error

### Potential ways to implement

Parse file path from the error reported by Metals and open it?
Or even implement this behavior directly in Metals?

**Comment by ckipp01** [comment]
Hey @susliko, thanks for creating this!

Yea, this is a good point and something we can totally fix.

> Probably, a more robust behavior here would be to open the existing file instead of showing the error

I think this is probably the way to go. We're already actually relying on Metals to create this file by using the new scala file command and just passing in a few things like you can see here:

https://github.com/scalameta/nvim-metals/blob/92f7451aa0dd0267027ab9a5850a4b7c1af33341/lua/metals.lua#L238-L242

 We could probably do a quick check to see if the worksheet exists first and if so, open it. Thinking about it, the process of creating this worksheet is pretty involved, and doesn't really need to be. I just-reused the logic since it already existed, but in reality we could just create a worksheet manually without even calling Metals.

**Comment by susliko** [comment]
I'd love to contribute this enhancement
Hopefully, will manage to find some time in the coming days
