### ISSUE TITLE
NeoVim Native I_Ctrl-N and I_Ctrl-P sometimes at first erases what had already been typed when `completeopt=menu,longest`

### ISSUE THREAD

**Issue by fl4shk** [scalameta/nvim-metals#599]
### Describe the bug

This happens even when I `set omnifunc=`. It seems to be mainly a problem with completing things like classInstance.member, for example.
I do not have `nvim-cmp` installed. I do not have any other completion plugins installed, either.

### Expected behavior

No erasure of the text I had typed in insert mode.

### Operating system

Linux

### Version of Metals

1.0.0

### Commit of nvim-metals

57cff9a240f3337129188997887d8848fe6022ad

**Comment by ckipp01** [comment]
Hey @fl4shk, thanks for the report. So I'm not 100% sure if this is actually just a metals specific thing or also relating to completion with Neovim. However, behind the scenes the reason this is happening is that with the completion that Metals is giving back you have a `textEdit` with a range, so that full text edit is just being applied, which replaces the existing word that you do have typed already. Do you see different behavior with this in other languages? If I'm not mistaken just testing this out with the typescript language server I see the same behavior? I know there are some more related settings in LSP capabilities, like `insertReplaceSupport`, but I'm not 100% sure this is what you're referring to. For example we have an issue on this in [here](https://github.com/scalameta/metals-feature-requests/issues/205). Also, could you provide a bit more info on the issue this is causing? For example if you have:

```scala

object Foo:
  val bar = "bar"
```

And you trigger a completion of:

```
Foo.ba<cursor>
```

I'm assuming you still result in `Foo.bar` which is the desired completion. Can you provide an example where this is problematic?

**Comment by ckipp01** [comment]
Actually digging in a bit more, this seems to be the recommended way to actual do the completion. For example you could compute the necessary text, but it requires more work server and client side. For example the docs actually say [this](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem):

```
	/**
	 * A string that should be inserted into a document when selecting
	 * this completion. When omitted the label is used as the insert text
	 * for this item.
	 *
	 * The `insertText` is subject to interpretation by the client side.
	 * Some tools might not take the string literally. For example
	 * VS Code when code complete is requested in this example
	 * `con<cursor position>` and a completion item with an `insertText` of
	 * `console` is provided it will only insert `sole`. Therefore it is
	 * recommended to use `textEdit` instead since it avoids additional client
	 * side interpretation.
	 */
	insertText?: string;
```

**Comment by fl4shk** [comment]
So,
```
Foo.ba<cursor>
```
sometimes results in just `Foo.` until I hit `Ctrl-N` a second time.

**Comment by fl4shk** [comment]
So upon further investigation, this seems to be caused by something in my `init.vim`. I will investigate further.

**Comment by ckipp01** [comment]
Hey @fl4shk just checking back in here. Is this something you ended up figuring out? Can this be closed?

**Comment by fl4shk** [comment]
Yeah it can be closed
