### ISSUE TITLE
Improve documentation for installation

### ISSUE THREAD

**Issue by dffuller** [scalameta/nvim-metals#636]
### Task

I could be missing something, but when I go to the readme, I see a lot of stuff on prerequisites, things you don't need and other things you might like to add, but nothing on actual installation into nvim.  The vim page on scalameta.org ([https://scalameta.org/metals/docs/editors/vim/](https://scalameta.org/metals/docs/editors/vim/)) points to [https://github.com/scalameta/nvim-metals#installation](https://github.com/scalameta/nvim-metals#installation), but there doesn't appear to be an \#installation section on that page.  This seems to be an oversight, but I'm having trouble figuring out how to install and the web and YouTube in particular aren't very helpful because everything seems to be centered about coc-metals.

**Comment by ckipp01** [comment]
> but nothing on actual installation into nvim

Thanks for the report @dffuller. I actually removed this section not that long ago since so many people use different package managers, that it's hard to show _exactly_ what someone should use since it differs ever so slightly. Plus, I have a full example [here](https://github.com/scalameta/nvim-metals/discussions/39#discussion-82302) that does show how to install. Did you see the example?

**Comment by dffuller** [comment]
After reading through it entirely, I can see that it does do installation. However, one must read through it entirely and, while I can't be certain of other's expectations, I will say that I don't generally expect that installation would be included in the body of a sample config script. Removing an installation section because it can't possibly cover all installation scenarios seems like a drastic decision, though.
